In [5]:
import pymongo
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["imdb"]
mycol = mydb["productions"]

In [ ]:
dblist = myclient.list_database_names() 
print(dblist)
collist = mydb.list_collection_names()
print(collist)
#exporting data from SQLITE to csv
#Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open imdb.db
sqlite> .headers on
sqlite> .mode csv
sqlite> .output people_extracted.csv
sqlite>  SELECT * FROM people;
.tables
cast         people       productions  ratings      titles   
sqlite> .headers on
sqlite> .mode csv
sqlite> .output titles_extracted.csv
sqlite>  SELECT * FROM titles;
sqlite> .output productions_extracted.csv
sqlite>  SELECT * FROM productions;
sqlite> .output cast_extracted.csv
sqlite>  SELECT * FROM cast;
sqlite> .output ratings_extracted.csv
sqlite>  SELECT * FROM ratings;
sqlite> .quit

'''
['admin', 'config', 'imdb', 'local']
['ratings', 'titles', 'prowithavg', 'cast', 'people', 'productions']
'''


C:\Users\tewbe>mongoimport --db imdb --collection productions --type csv --headerline --file Downloads\files\files\productions.csv
C:\Users\tewbe>mongoimport --db imdb --collection cast --type csv --headerline --file Downloads\files\files\cast.csv
C:\Users\tewbe>mongoimport --db imdb --collection people --type csv --headerline --file Downloads\files\files\people.csv
C:\Users\tewbe>mongoimport --db imdb --collection ratings --type csv --headerline --file Downloads\files\files\ratings.csv
#2021-08-01T10:56:48.578-0400    connected to: mongodb://localhost/
#2021-08-01T10:56:49.000-0400    15720 document(s) imported successfully. 0 document(s) failed to import.

C:\Users\tewbe>mongoimport --db imdb --collection people --type csv --headerline --file Downloads\files\files\people.csv
'''
2021-08-01T10:57:45.505-0400    connected to: mongodb://localhost/
2021-08-01T10:57:48.505-0400    [###################.....] imdb.people       7.40MB/9.34MB (79.3%)
2021-08-01T10:57:49.243-0400    [########################] imdb.people       9.34MB/9.34MB (100.0%)
2021-08-01T10:57:49.243-0400    107066 document(s) imported successfully. 0 document(s) failed to import.
'''

#A
y = mycol.find({"TITLE_TYPE":"tvMovie","RUNTIME_MINUTES":60}).limit(5)
for x in y:
  print(x)

y = mycol.find({"TITLE_TYPE":"Movie","START_YEAR":{"$gt":2018},"genre":{"$eq":"Documentary"}}).limit(15)
for x in y:
  print(x)

'''
{'_id': ObjectId('610354757ffc3b194b528a71'), 'TCONST': 'tt10006422', 'TITLE_TYPE': 'tvMovie', 'PRIMARY_TITLE': 'Warrior Women of Dahomey', 'ORIGINAL_TITLE': 'Warrior Women of Dahomey', 'START_YEAR': 2019, 'END_YEAR': 0, 'RUNTIME_MINUTES': 60.0, 'GENRES': 'Documentary'}
{'_id': ObjectId('610354757ffc3b194b52ae57'), 'TCONST': 'tt10050182', 'TITLE_TYPE': 'tvMovie', 'PRIMARY_TITLE': 'Special Operations: India Surgical Strike', 'ORIGINAL_TITLE': 'Special Operations: India Surgical Strike', 'START_YEAR': 2018, 'END_YEAR': 0, 'RUNTIME_MINUTES': 60.0, 'GENRES': 'Documentary'}
{'_id': ObjectId('610354757ffc3b194b52ae6a'), 'TCONST': 'tt10050268', 'TITLE_TYPE': 'tvMovie', 'PRIMARY_TITLE': 'Special Operations: India Myanmar', 'ORIGINAL_TITLE': 'Special Operations: India Myanmar', 'START_YEAR': 2018, 'END_YEAR': 0, 'RUNTIME_MINUTES': 60.0, 'GENRES': 'Documentary'}
{'_id': ObjectId('610354757ffc3b194b52ce43'), 'TCONST': 'tt10090544', 'TITLE_TYPE': 'tvMovie', 'PRIMARY_TITLE': 'Le Pigalle: Une histoire populaire de Paris', 'ORIGINAL_TITLE': 'Le Pigalle: Une histoire populaire de Paris', 'START_YEAR': 2017, 'END_YEAR': 0, 'RUNTIME_MINUTES': 60.0, 'GENRES': 'Documentary'}
{'_id': ObjectId('610354757ffc3b194b52e636'), 'TCONST': 'tt10119466', 'TITLE_TYPE': 'tvMovie', 'PRIMARY_TITLE': "America's Child Brides", 'ORIGINAL_TITLE': "America's Child Brides", 'START_YEAR': 2019, 'END_YEAR': 0, 'RUNTIME_MINUTES': 60.0, 'GENRES': 'Documentary'}
'''
y = mycol.find({"TITLE_TYPE":"movie","START_YEAR":{"$gte":"2018"},"GENRES":{"$eq":"Documentary"}}).limit(15)
for x in y:
  print(x)
'''
{'_id': ObjectId('6106b52b88cb145a6b259bf3'), 'TCONST': 'tt0170651', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'T.G.M. - osvoboditel', 'ORIGINAL_TITLE': 'T.G.M. - osvoboditel', 'START_YEAR': '2018', 'END_YEAR': '0', 'RUNTIME_MINUTES': '60.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259bfb'), 'TCONST': 'tt0262759', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Seven Jews from My Class', 'ORIGINAL_TITLE': 'Siedmiu Zydów z mojej klasy', 'START_YEAR': '2018', 'END_YEAR': '0', 'RUNTIME_MINUTES': '40.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259c49'), 'TCONST': 'tt0846775', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Cine Manifest', 'ORIGINAL_TITLE': 'Cine Manifest', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '75.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259c51'), 'TCONST': 'tt0891581', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'RxCannabis: A Freedom Tale', 'ORIGINAL_TITLE': 'RxCannabis: A Freedom Tale', 'START_YEAR': '2018', 'END_YEAR': '0', 'RUNTIME_MINUTES': '83.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259cea'), 'TCONST': 'tt10001870', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Disrupted Land', 'ORIGINAL_TITLE': 'Disrupted Land', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '77.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259e63'), 'TCONST': 'tt10003978', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Fiddler: A Miracle of Miracles', 'ORIGINAL_TITLE': 'Fiddler: A Miracle of Miracles', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '97.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b259ec3'), 'TCONST': 'tt10004372', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Soccer in the City', 'ORIGINAL_TITLE': 'Soccer in the City', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '82.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a057'), 'TCONST': 'tt10006122', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Debout', 'ORIGINAL_TITLE': 'Debout', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '85.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a079'), 'TCONST': 'tt10006274', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Feeling of revulsion', 'ORIGINAL_TITLE': 'Feeling of revulsion', 'START_YEAR': '2018', 'END_YEAR': '0', 'RUNTIME_MINUTES': '0.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a118'), 'TCONST': 'tt10006874', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Weltweite Freundschaften', 'ORIGINAL_TITLE': 'Weltweite Freundschaften', 'START_YEAR': '2018', 'END_YEAR': '0', 'RUNTIME_MINUTES': '0.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a19c'), 'TCONST': 'tt10007820', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'On the Trail of Bigfoot', 'ORIGINAL_TITLE': 'On the Trail of Bigfoot', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '0.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a1be'), 'TCONST': 'tt10007978', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Terror in the Skies', 'ORIGINAL_TITLE': 'Terror in the Skies', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '67.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a1ff'), 'TCONST': 'tt10008304', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'In Our Blood - El Comienzo de Todo, Àlex Crivillé', 'ORIGINAL_TITLE': 'In Our Blood - El Comienzo de Todo, Àlex Crivillé', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '0.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a238'), 'TCONST': 'tt10008602', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'In Our Blood - Sin Límite, Marc Márquez', 'ORIGINAL_TITLE': 'In Our Blood - Sin Límite, Marc Márquez', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '0.0', 'GENRES': 'Documentary'}
{'_id': ObjectId('6106b52b88cb145a6b25a289'), 'TCONST': 'tt10008996', 'TITLE_TYPE': 'movie', 'PRIMARY_TITLE': 'Troublemaker', 'ORIGINAL_TITLE': 'Troublemaker', 'START_YEAR': '2019', 'END_YEAR': '0', 'RUNTIME_MINUTES': '56.0', 'GENRES': 'Documentary'}
'''

#B
mydict ={"TITLE_TYPE"  :  'vlog',  "START_YEAR"  :  2021, "END_YEAR" : 2022, "RUNTIME_MINUTES" : 15, "NO_SCHEMA" : "Yes"} 
x = mycol.insert_one(mydict)
print(x)
x=mycol.find(mydict)
for y in x:
  print(y)
'''
<pymongo.results.InsertOneResult object at 0x0000021E97C7C240>
{'_id': ObjectId('6106becb60a2b08a6a31d73c'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
'''
mydict2=[{"TITLE_TYPE"  :  'vlog',  "START_YEAR"  :  2021, "END_YEAR"  :  2022,  "RUNTIME_MINUTES"  :  15},  {  "TITLE_TYPE"  :  'vlog', "START_YEAR" : 2019, "END_YEAR" : 2022, "RUNTIME_MINUTES" : 25}]
x=mycol.insert_many(mydict2)
print(x)

y = mycol.find({"$or":mydict2})
for x in y:
  print(x)
'''
<pymongo.results.InsertManyResult object at 0x00000243D6405600>
{'_id': ObjectId('6106c0ee3715dfa284fd17bf'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15}
{'_id': ObjectId('6106c0ee3715dfa284fd17c0'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2019, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 25}
'''
y = mycol.find({"TITLE_TYPE"  :  'vlog'})
for x in y:
  print(x)
'''
['titles', 'cast', 'people', 'ratings', 'productions']
{'_id': ObjectId('6106bdf60a76e9d1f443aef7'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106be07f6120a66df36b716'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106be4b8401685d489f69b5'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106bea21fe254f68c96d485'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106becb60a2b08a6a31d73c'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106befd1891fb4ca2bae01f'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('6106c014a674b3be23432d94'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15}
{'_id': ObjectId('6106c014a674b3be23432d95'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2019, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 25}
{'_id': ObjectId('6106c0ee3715dfa284fd17bf'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15}
{'_id': ObjectId('6106c0ee3715dfa284fd17c0'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2019, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 25}'''

In [ ]:
#C
myquery = { "START_YEAR"  :{"$eq": 2018 }}
newvalues = { "$set": { "TITLE_TYPE": "vlog" } }
y=mycol.update(myquery, newvalues)
print(y)
y = mycol.find({"TITLE_TYPE":"vlog"}).limit(5)
for x in y:
  print(x)

y = mycol.find({"TITLE_TYPE":"vlog"},{"TCONST":1, "_id":1})
for x in y:
  print(x)

for x in y:
  ans = mycol.update_one({ "TCONST":{ "$eq":x } } ,{ "$set": {"TITLE_TYPE" :"movie"}});
  print(ans)
y = mycol.find({"TITLE_TYPE":"vlog"})
for x in y:
  print(x)

myquery = {"TITLE_TYPE":"vlog"}

x = mycol.delete_many(myquery)

print(x.deleted_count, " documents deleted.")
y = mycol.find({"TITLE_TYPE"  :  'vlog'})
for x in y:
  print(x)
'''
{'_id': ObjectId('61070971a94e90ddf824cccd'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('61070971a94e90ddf824ccce'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15}
{'_id': ObjectId('61070971a94e90ddf824cccf'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2019, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 25}
{'_id': ObjectId('61070971a94e90ddf824cccd')}
{'_id': ObjectId('61070971a94e90ddf824ccce')}
{'_id': ObjectId('61070971a94e90ddf824cccf')}
{'_id': ObjectId('61070971a94e90ddf824cccd'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15, 'NO_SCHEMA': 'Yes'}
{'_id': ObjectId('61070971a94e90ddf824ccce'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2021, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 15}
{'_id': ObjectId('61070971a94e90ddf824cccf'), 'TITLE_TYPE': 'vlog', 'START_YEAR': 2019, 'END_YEAR': 2022, 'RUNTIME_MINUTES': 25}
3  documents deleted.
'''

In [91]:
# Aggregation D
mycol.aggregate([
{"$lookup":{
"from":"ratings",
"localField":"TCONST",
"foreignField":"TCONST",
"as":"new"
}},

{"$unwind": "$new"},
{"$project": {"TCONST": 1,"TITLE_TYPE": 1,"RUNTIME_MINUTES": 1,"AVG":"new.AVG_RATING"}
},
{ "$out" : " productions_with_ratings"}
])
mycol = mydb["productions_with_ratings"]
y = mycol.find().limit(10)
for x in y:
  print(x)

'''
{'_id': ObjectId('6106b52b88cb145a6b259be9'), 'TCONST': 'tt0069049', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '122.0', 'new': {'AVG_RATING': 6.9}}
{'_id': ObjectId('6106b52b88cb145a6b259bea'), 'TCONST': 'tt0069204', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '0.0', 'new': {'AVG_RATING': 6.1}}
{'_id': ObjectId('6106b52b88cb145a6b259beb'), 'TCONST': 'tt0085953', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '84.0', 'new': {'AVG_RATING': 6.3}}
{'_id': ObjectId('6106b52b88cb145a6b259bec'), 'TCONST': 'tt0091490', 'TITLE_TYPE': 'short', 'RUNTIME_MINUTES': '20.0', 'new': {'AVG_RATING': 5.9}}
{'_id': ObjectId('6106b52b88cb145a6b259bed'), 'TCONST': 'tt0100275', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '80.0', 'new': {'AVG_RATING': 6.6}}
{'_id': ObjectId('6106b52b88cb145a6b259bef'), 'TCONST': 'tt0112502', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '0.0', 'new': {'AVG_RATING': 4.2}}
{'_id': ObjectId('6106b52b88cb145a6b259bf0'), 'TCONST': 'tt0116991', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '0.0', 'new': {'AVG_RATING': 7.4}}
{'_id': ObjectId('6106b52b88cb145a6b259bf1'), 'TCONST': 'tt0129960', 'TITLE_TYPE': 'tvMovie', 'RUNTIME_MINUTES': '0.0', 'new': {'AVG_RATING': 7.2}}
{'_id': ObjectId('6106b52b88cb145a6b259bf2'), 'TCONST': 'tt0137204', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '83.0', 'new': {'AVG_RATING': 8.6}}
{'_id': ObjectId('6106b52b88cb145a6b259bf3'), 'TCONST': 'tt0170651', 'TITLE_TYPE': 'movie', 'RUNTIME_MINUTES': '60.0', 'new': {'AVG_RATING': 7.5}}
'''

<pymongo.cursor.Cursor object at 0x7fb76efb9610>